// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// </summary>
    public partial interface IPMClient : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the ICalendariosFabrica.
        /// </summary>
        ICalendariosFabrica CalendariosFabrica { get; }

        /// <summary>
        /// Gets the ICapacidades.
        /// </summary>
        ICapacidades Capacidades { get; }

        /// <summary>
        /// Gets the ICarros.
        /// </summary>
        ICarros Carros { get; }

        /// <summary>
        /// Gets the ICatalogos.
        /// </summary>
        ICatalogos Catalogos { get; }

        /// <summary>
        /// Gets the ICategoriasEquipamento.
        /// </summary>
        ICategoriasEquipamento CategoriasEquipamento { get; }

        /// <summary>
        /// Gets the ICategoriasPontoMedicao.
        /// </summary>
        ICategoriasPontoMedicao CategoriasPontoMedicao { get; }

        /// <summary>
        /// Gets the ICentrosCusto.
        /// </summary>
        ICentrosCusto CentrosCusto { get; }

        /// <summary>
        /// Gets the ICentrosLocalizacao.
        /// </summary>
        ICentrosLocalizacao CentrosLocalizacao { get; }

        /// <summary>
        /// Gets the ICentroTrabalhos.
        /// </summary>
        ICentroTrabalhos CentroTrabalhos { get; }

        /// <summary>
        /// Gets the IChavesControle.
        /// </summary>
        IChavesControle ChavesControle { get; }

        /// <summary>
        /// Gets the IClassificacoes.
        /// </summary>
        IClassificacoes Classificacoes { get; }

        /// <summary>
        /// Gets the ICodes.
        /// </summary>
        ICodes Codes { get; }

        /// <summary>
        /// Gets the ICodigosABC.
        /// </summary>
        ICodigosABC CodigosABC { get; }

        /// <summary>
        /// Gets the IComplementos.
        /// </summary>
        IComplementos Complementos { get; }

        /// <summary>
        /// Gets the IDiagnosticos.
        /// </summary>
        IDiagnosticos Diagnosticos { get; }

        /// <summary>
        /// Gets the IDocumentos.
        /// </summary>
        IDocumentos Documentos { get; }

        /// <summary>
        /// Gets the IElementosPEP.
        /// </summary>
        IElementosPEP ElementosPEP { get; }

        /// <summary>
        /// Gets the IEmpregados.
        /// </summary>
        IEmpregados Empregados { get; }

        /// <summary>
        /// Gets the IEntregaTremOperations.
        /// </summary>
        IEntregaTremOperations EntregaTremOperations { get; }

        /// <summary>
        /// Gets the IEquipamentos.
        /// </summary>
        IEquipamentos Equipamentos { get; }

        /// <summary>
        /// Gets the IEstrategias.
        /// </summary>
        IEstrategias Estrategias { get; }

        /// <summary>
        /// Gets the IEventosGerador.
        /// </summary>
        IEventosGerador EventosGerador { get; }

        /// <summary>
        /// Gets the IFrotas.
        /// </summary>
        IFrotas Frotas { get; }

        /// <summary>
        /// Gets the IGrupoCodes.
        /// </summary>
        IGrupoCodes GrupoCodes { get; }

        /// <summary>
        /// Gets the IIntervencoesOperacao.
        /// </summary>
        IIntervencoesOperacao IntervencoesOperacao { get; }

        /// <summary>
        /// Gets the ILinhas.
        /// </summary>
        ILinhas Linhas { get; }

        /// <summary>
        /// Gets the IListasTarefas.
        /// </summary>
        IListasTarefas ListasTarefas { get; }

        /// <summary>
        /// Gets the IListaTarefaOperacaoComponentes.
        /// </summary>
        IListaTarefaOperacaoComponentes ListaTarefaOperacaoComponentes { get; }

        /// <summary>
        /// Gets the IListaTarefaOperacoes.
        /// </summary>
        IListaTarefaOperacoes ListaTarefaOperacoes { get; }

        /// <summary>
        /// Gets the ILocaisInstalacao.
        /// </summary>
        ILocaisInstalacao LocaisInstalacao { get; }

        /// <summary>
        /// Gets the ILogLogins.
        /// </summary>
        ILogLogins LogLogins { get; }

        /// <summary>
        /// Gets the IMaosDeObra.
        /// </summary>
        IMaosDeObra MaosDeObra { get; }

        /// <summary>
        /// Gets the IMAPs.
        /// </summary>
        IMAPs MAPs { get; }

        /// <summary>
        /// Gets the IMarcos.
        /// </summary>
        IMarcos Marcos { get; }

        /// <summary>
        /// Gets the IMateriaisOperacao.
        /// </summary>
        IMateriaisOperacao MateriaisOperacao { get; }

        /// <summary>
        /// Gets the IMaterials.
        /// </summary>
        IMaterials Materials { get; }

        /// <summary>
        /// Gets the IMedidasNota.
        /// </summary>
        IMedidasNota MedidasNota { get; }

        /// <summary>
        /// Gets the IModelosLinear.
        /// </summary>
        IModelosLinear ModelosLinear { get; }

        /// <summary>
        /// Gets the IMotivoEntregaOperations.
        /// </summary>
        IMotivoEntregaOperations MotivoEntregaOperations { get; }

        /// <summary>
        /// Gets the INotas.
        /// </summary>
        INotas Notas { get; }

        /// <summary>
        /// Gets the IOperacoesOrdem.
        /// </summary>
        IOperacoesOrdem OperacoesOrdem { get; }

        /// <summary>
        /// Gets the IOrdens.
        /// </summary>
        IOrdens Ordens { get; }

        /// <summary>
        /// Gets the IParceiroOperations.
        /// </summary>
        IParceiroOperations ParceiroOperations { get; }

        /// <summary>
        /// Gets the IPatioLinhaOperations.
        /// </summary>
        IPatioLinhaOperations PatioLinhaOperations { get; }

        /// <summary>
        /// Gets the IPatios.
        /// </summary>
        IPatios Patios { get; }

        /// <summary>
        /// Gets the IPontosMedicao.
        /// </summary>
        IPontosMedicao PontosMedicao { get; }

        /// <summary>
        /// Gets the IPosicoes.
        /// </summary>
        IPosicoes Posicoes { get; }

        /// <summary>
        /// Gets the IPrioridades.
        /// </summary>
        IPrioridades Prioridades { get; }

        /// <summary>
        /// Gets the IProgramacaoOperations.
        /// </summary>
        IProgramacaoOperations ProgramacaoOperations { get; }

        /// <summary>
        /// Gets the ISistemaAplicacaoOperations.
        /// </summary>
        ISistemaAplicacaoOperations SistemaAplicacaoOperations { get; }

        /// <summary>
        /// Gets the ISistemaEmpresaOperations.
        /// </summary>
        ISistemaEmpresaOperations SistemaEmpresaOperations { get; }

        /// <summary>
        /// Gets the ISistemaLogErrorOperations.
        /// </summary>
        ISistemaLogErrorOperations SistemaLogErrorOperations { get; }

        /// <summary>
        /// Gets the ISistemaLogLoginOperations.
        /// </summary>
        ISistemaLogLoginOperations SistemaLogLoginOperations { get; }

        /// <summary>
        /// Gets the ISistemaLogOperacoesOperations.
        /// </summary>
        ISistemaLogOperacoesOperations SistemaLogOperacoesOperations { get; }

        /// <summary>
        /// Gets the ISistemaLogOperacoesItemOperations.
        /// </summary>
        ISistemaLogOperacoesItemOperations SistemaLogOperacoesItemOperations { get; }

        /// <summary>
        /// Gets the ISistemaModuloOperations.
        /// </summary>
        ISistemaModuloOperations SistemaModuloOperations { get; }

        /// <summary>
        /// Gets the ISistemaPerfilOperations.
        /// </summary>
        ISistemaPerfilOperations SistemaPerfilOperations { get; }

        /// <summary>
        /// Gets the ISistemaPerfilItemOperations.
        /// </summary>
        ISistemaPerfilItemOperations SistemaPerfilItemOperations { get; }

        /// <summary>
        /// Gets the ISistemas.
        /// </summary>
        ISistemas Sistemas { get; }

        /// <summary>
        /// Gets the ISistemaTabelaOperations.
        /// </summary>
        ISistemaTabelaOperations SistemaTabelaOperations { get; }

        /// <summary>
        /// Gets the ISistemaTabelaCampoOperations.
        /// </summary>
        ISistemaTabelaCampoOperations SistemaTabelaCampoOperations { get; }

        /// <summary>
        /// Gets the ISistemaTipoDadoOperations.
        /// </summary>
        ISistemaTipoDadoOperations SistemaTipoDadoOperations { get; }

        /// <summary>
        /// Gets the ISistemaTipoLogOperations.
        /// </summary>
        ISistemaTipoLogOperations SistemaTipoLogOperations { get; }

        /// <summary>
        /// Gets the ISistemaUsuarioOperations.
        /// </summary>
        ISistemaUsuarioOperations SistemaUsuarioOperations { get; }

        /// <summary>
        /// Gets the ISistemaUsuarioModuloOperations.
        /// </summary>
        ISistemaUsuarioModuloOperations SistemaUsuarioModuloOperations { get; }

        /// <summary>
        /// Gets the IStatusCopeses.
        /// </summary>
        IStatusCopeses StatusCopeses { get; }

        /// <summary>
        /// Gets the IStatusEntregaTremOperations.
        /// </summary>
        IStatusEntregaTremOperations StatusEntregaTremOperations { get; }

        /// <summary>
        /// Gets the IStatusMedidas.
        /// </summary>
        IStatusMedidas StatusMedidas { get; }

        /// <summary>
        /// Gets the IStatusOperacoes.
        /// </summary>
        IStatusOperacoes StatusOperacoes { get; }

        /// <summary>
        /// Gets the IStatusPericias.
        /// </summary>
        IStatusPericias StatusPericias { get; }

        /// <summary>
        /// Gets the IStatusProgramacaoTremOperations.
        /// </summary>
        IStatusProgramacaoTremOperations StatusProgramacaoTremOperations { get; }

        /// <summary>
        /// Gets the IStatusSistemas.
        /// </summary>
        IStatusSistemas StatusSistemas { get; }

        /// <summary>
        /// Gets the IStatusTremOperations.
        /// </summary>
        IStatusTremOperations StatusTremOperations { get; }

        /// <summary>
        /// Gets the IStatusUsuarios.
        /// </summary>
        IStatusUsuarios StatusUsuarios { get; }

        /// <summary>
        /// Gets the ITipoNotas.
        /// </summary>
        ITipoNotas TipoNotas { get; }

        /// <summary>
        /// Gets the ITiposCapacidade.
        /// </summary>
        ITiposCapacidade TiposCapacidade { get; }

        /// <summary>
        /// Gets the ITiposCentroTrabalho.
        /// </summary>
        ITiposCentroTrabalho TiposCentroTrabalho { get; }

        /// <summary>
        /// Gets the ITiposMarcador.
        /// </summary>
        ITiposMarcador TiposMarcador { get; }

        /// <summary>
        /// Gets the ITiposOrdem.
        /// </summary>
        ITiposOrdem TiposOrdem { get; }

        /// <summary>
        /// Gets the ITrems.
        /// </summary>
        ITrems Trems { get; }

        /// <summary>
        /// Gets the IUnidadesMedida.
        /// </summary>
        IUnidadesMedida UnidadesMedida { get; }

        /// <summary>
        /// Gets the IZonas.
        /// </summary>
        IZonas Zonas { get; }

    }
}
