// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CentroLocalizacao
    {
        /// <summary>
        /// Initializes a new instance of the CentroLocalizacao class.
        /// </summary>
        public CentroLocalizacao() { }

        /// <summary>
        /// Initializes a new instance of the CentroLocalizacao class.
        /// </summary>
        public CentroLocalizacao(int? idCtLocalizacao = default(int?), string cdSap = default(string), string dsCtLocalizacao = default(string), BaseModel baseModel = default(BaseModel))
        {
            IdCtLocalizacao = idCtLocalizacao;
            CdSap = cdSap;
            DsCtLocalizacao = dsCtLocalizacao;
            BaseModel = baseModel;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_ct_localizacao")]
        public int? IdCtLocalizacao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cd_sap")]
        public string CdSap { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ds_ct_localizacao")]
        public string DsCtLocalizacao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseModel")]
        public BaseModel BaseModel { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.CdSap != null)
            {
                if (this.CdSap.Length > 4)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CdSap", 4);
                }
                if (this.CdSap.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CdSap", 0);
                }
            }
            if (this.DsCtLocalizacao != null)
            {
                if (this.DsCtLocalizacao.Length > 50)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "DsCtLocalizacao", 50);
                }
                if (this.DsCtLocalizacao.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "DsCtLocalizacao", 0);
                }
            }
        }
    }
}
