// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CentroCusto
    {
        /// <summary>
        /// Initializes a new instance of the CentroCusto class.
        /// </summary>
        public CentroCusto() { }

        /// <summary>
        /// Initializes a new instance of the CentroCusto class.
        /// </summary>
        public CentroCusto(int? idCentroCusto = default(int?), string cdSap = default(string), string dsCentroCusto = default(string), string dsCompletaCentroCusto = default(string), string nmUsuarioAlteracao = default(string), DateTime? dtAlteracaoRegistro = default(DateTime?), double? nrFator = default(double?), string sgCentroCusto = default(string), bool? stAtivo = default(bool?), string arCentroCusto = default(string), DateTime? dtCarga = default(DateTime?), string ctCustoAnterior = default(string), BaseModel baseModel = default(BaseModel))
        {
            IdCentroCusto = idCentroCusto;
            CdSap = cdSap;
            DsCentroCusto = dsCentroCusto;
            DsCompletaCentroCusto = dsCompletaCentroCusto;
            NmUsuarioAlteracao = nmUsuarioAlteracao;
            DtAlteracaoRegistro = dtAlteracaoRegistro;
            NrFator = nrFator;
            SgCentroCusto = sgCentroCusto;
            StAtivo = stAtivo;
            ArCentroCusto = arCentroCusto;
            DtCarga = dtCarga;
            CtCustoAnterior = ctCustoAnterior;
            BaseModel = baseModel;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_centro_custo")]
        public int? IdCentroCusto { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cd_sap")]
        public string CdSap { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ds_centro_custo")]
        public string DsCentroCusto { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ds_completa_centro_custo")]
        public string DsCompletaCentroCusto { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nm_usuario_alteracao")]
        public string NmUsuarioAlteracao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dt_alteracao_registro")]
        public DateTime? DtAlteracaoRegistro { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nr_fator")]
        public double? NrFator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sg_centro_custo")]
        public string SgCentroCusto { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "st_ativo")]
        public bool? StAtivo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ar_centro_custo")]
        public string ArCentroCusto { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dt_carga")]
        public DateTime? DtCarga { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ct_custo_anterior")]
        public string CtCustoAnterior { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseModel")]
        public BaseModel BaseModel { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.CdSap != null)
            {
                if (this.CdSap.Length > 10)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CdSap", 10);
                }
                if (this.CdSap.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CdSap", 0);
                }
            }
            if (this.DsCentroCusto != null)
            {
                if (this.DsCentroCusto.Length > 30)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "DsCentroCusto", 30);
                }
                if (this.DsCentroCusto.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "DsCentroCusto", 0);
                }
            }
            if (this.DsCompletaCentroCusto != null)
            {
                if (this.DsCompletaCentroCusto.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "DsCompletaCentroCusto", 255);
                }
                if (this.DsCompletaCentroCusto.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "DsCompletaCentroCusto", 0);
                }
            }
            if (this.NmUsuarioAlteracao != null)
            {
                if (this.NmUsuarioAlteracao.Length > 12)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "NmUsuarioAlteracao", 12);
                }
                if (this.NmUsuarioAlteracao.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "NmUsuarioAlteracao", 0);
                }
            }
            if (this.SgCentroCusto != null)
            {
                if (this.SgCentroCusto.Length > 15)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "SgCentroCusto", 15);
                }
                if (this.SgCentroCusto.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "SgCentroCusto", 0);
                }
            }
            if (this.ArCentroCusto != null)
            {
                if (this.ArCentroCusto.Length > 15)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "ArCentroCusto", 15);
                }
                if (this.ArCentroCusto.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "ArCentroCusto", 0);
                }
            }
            if (this.CtCustoAnterior != null)
            {
                if (this.CtCustoAnterior.Length > 5)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CtCustoAnterior", 5);
                }
                if (this.CtCustoAnterior.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CtCustoAnterior", 0);
                }
            }
        }
    }
}
