// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CodigoABC
    {
        /// <summary>
        /// Initializes a new instance of the CodigoABC class.
        /// </summary>
        public CodigoABC() { }

        /// <summary>
        /// Initializes a new instance of the CodigoABC class.
        /// </summary>
        public CodigoABC(int? idAbc = default(int?), string cdSap = default(string), string dsAbc = default(string), BaseModel baseModel = default(BaseModel))
        {
            IdAbc = idAbc;
            CdSap = cdSap;
            DsAbc = dsAbc;
            BaseModel = baseModel;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_abc")]
        public int? IdAbc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cd_sap")]
        public string CdSap { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ds_abc")]
        public string DsAbc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseModel")]
        public BaseModel BaseModel { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.CdSap != null)
            {
                if (this.CdSap.Length > 1)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CdSap", 1);
                }
                if (this.CdSap.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CdSap", 0);
                }
            }
            if (this.DsAbc != null)
            {
                if (this.DsAbc.Length > 50)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "DsAbc", 50);
                }
                if (this.DsAbc.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "DsAbc", 0);
                }
            }
        }
    }
}
