// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Deposito
    {
        /// <summary>
        /// Initializes a new instance of the Deposito class.
        /// </summary>
        public Deposito() { }

        /// <summary>
        /// Initializes a new instance of the Deposito class.
        /// </summary>
        public Deposito(int? idDeposito = default(int?), BaseModel baseModel = default(BaseModel))
        {
            IdDeposito = idDeposito;
            BaseModel = baseModel;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_deposito")]
        public int? IdDeposito { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseModel")]
        public BaseModel BaseModel { get; set; }

    }
}
