// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EntregaTrem
    {
        /// <summary>
        /// Initializes a new instance of the EntregaTrem class.
        /// </summary>
        public EntregaTrem() { }

        /// <summary>
        /// Initializes a new instance of the EntregaTrem class.
        /// </summary>
        public EntregaTrem(int? idEntrega = default(int?), int? idMotivoEntregaOcorFk = default(int?), int? idMotivoEntregaProgFk = default(int?), int? idMotivoEntregaInspecaoFk = default(int?), int? idTremFk = default(int?), DateTime? dtEntrega = default(DateTime?), DateTime? hrEntrega = default(DateTime?), int? idPatioFk = default(int?), int? idLinEntrega = default(int?), int? idCtTrab = default(int?), int? idRespEntrega = default(int?), DateTime? dtCancelamento = default(DateTime?), DateTime? hrCancelamento = default(DateTime?), int? idRespCancelamento = default(int?), DateTime? dtLiberacao = default(DateTime?), DateTime? hrLiberacao = default(DateTime?), int? idRespLiberacao = default(int?), int? stEntregaTrem = default(int?), IList<Nota> notas = default(IList<Nota>), IList<Programacao> programacao = default(IList<Programacao>), string dsMotivoCancelamento = default(string), BaseModel baseModel = default(BaseModel), MotivoEntrega motivoEntregaOcorrencia = default(MotivoEntrega), MotivoEntrega motivoEntregaProgramacao = default(MotivoEntrega), MotivoEntrega motivoEntregaInspecao = default(MotivoEntrega), Trem trem = default(Trem), Patio patio = default(Patio), Linha linha = default(Linha), CentroTrabalho centroTrabalho = default(CentroTrabalho), Empregado respEntrega = default(Empregado), Empregado respCancelamento = default(Empregado), Empregado respLiberacao = default(Empregado), StatusEntregaTrem statusEntregaTrem = default(StatusEntregaTrem))
        {
            IdEntrega = idEntrega;
            IdMotivoEntregaOcorFk = idMotivoEntregaOcorFk;
            IdMotivoEntregaProgFk = idMotivoEntregaProgFk;
            IdMotivoEntregaInspecaoFk = idMotivoEntregaInspecaoFk;
            IdTremFk = idTremFk;
            DtEntrega = dtEntrega;
            HrEntrega = hrEntrega;
            IdPatioFk = idPatioFk;
            IdLinEntrega = idLinEntrega;
            IdCtTrab = idCtTrab;
            IdRespEntrega = idRespEntrega;
            DtCancelamento = dtCancelamento;
            HrCancelamento = hrCancelamento;
            IdRespCancelamento = idRespCancelamento;
            DtLiberacao = dtLiberacao;
            HrLiberacao = hrLiberacao;
            IdRespLiberacao = idRespLiberacao;
            StEntregaTrem = stEntregaTrem;
            Notas = notas;
            Programacao = programacao;
            DsMotivoCancelamento = dsMotivoCancelamento;
            BaseModel = baseModel;
            MotivoEntregaOcorrencia = motivoEntregaOcorrencia;
            MotivoEntregaProgramacao = motivoEntregaProgramacao;
            MotivoEntregaInspecao = motivoEntregaInspecao;
            Trem = trem;
            Patio = patio;
            Linha = linha;
            CentroTrabalho = centroTrabalho;
            RespEntrega = respEntrega;
            RespCancelamento = respCancelamento;
            RespLiberacao = respLiberacao;
            StatusEntregaTrem = statusEntregaTrem;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_entrega")]
        public int? IdEntrega { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_motivo_entrega_ocor_fk")]
        public int? IdMotivoEntregaOcorFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_motivo_entrega_prog_fk")]
        public int? IdMotivoEntregaProgFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_motivo_entrega_inspecao_fk")]
        public int? IdMotivoEntregaInspecaoFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_trem_fk")]
        public int? IdTremFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dt_entrega")]
        public DateTime? DtEntrega { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hr_entrega")]
        public DateTime? HrEntrega { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_patio_fk")]
        public int? IdPatioFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_lin_entrega")]
        public int? IdLinEntrega { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_ct_trab")]
        public int? IdCtTrab { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_resp_entrega")]
        public int? IdRespEntrega { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dt_cancelamento")]
        public DateTime? DtCancelamento { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hr_cancelamento")]
        public DateTime? HrCancelamento { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_resp_cancelamento")]
        public int? IdRespCancelamento { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dt_liberacao")]
        public DateTime? DtLiberacao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hr_liberacao")]
        public DateTime? HrLiberacao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_resp_liberacao")]
        public int? IdRespLiberacao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "st_entrega_trem")]
        public int? StEntregaTrem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Notas")]
        public IList<Nota> Notas { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Programacao")]
        public IList<Programacao> Programacao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ds_motivo_cancelamento")]
        public string DsMotivoCancelamento { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseModel")]
        public BaseModel BaseModel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MotivoEntregaOcorrencia")]
        public MotivoEntrega MotivoEntregaOcorrencia { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MotivoEntregaProgramacao")]
        public MotivoEntrega MotivoEntregaProgramacao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MotivoEntregaInspecao")]
        public MotivoEntrega MotivoEntregaInspecao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Trem")]
        public Trem Trem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Patio")]
        public Patio Patio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Linha")]
        public Linha Linha { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CentroTrabalho")]
        public CentroTrabalho CentroTrabalho { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RespEntrega")]
        public Empregado RespEntrega { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RespCancelamento")]
        public Empregado RespCancelamento { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RespLiberacao")]
        public Empregado RespLiberacao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StatusEntregaTrem")]
        public StatusEntregaTrem StatusEntregaTrem { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Notas != null)
            {
                foreach (var element in this.Notas)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (this.Programacao != null)
            {
                foreach (var element1 in this.Programacao)
                {
                    if (element1 != null)
                    {
                        element1.Validate();
                    }
                }
            }
            if (this.MotivoEntregaOcorrencia != null)
            {
                this.MotivoEntregaOcorrencia.Validate();
            }
            if (this.MotivoEntregaProgramacao != null)
            {
                this.MotivoEntregaProgramacao.Validate();
            }
            if (this.MotivoEntregaInspecao != null)
            {
                this.MotivoEntregaInspecao.Validate();
            }
            if (this.Trem != null)
            {
                this.Trem.Validate();
            }
            if (this.Patio != null)
            {
                this.Patio.Validate();
            }
            if (this.Linha != null)
            {
                this.Linha.Validate();
            }
            if (this.CentroTrabalho != null)
            {
                this.CentroTrabalho.Validate();
            }
            if (this.RespEntrega != null)
            {
                this.RespEntrega.Validate();
            }
            if (this.RespCancelamento != null)
            {
                this.RespCancelamento.Validate();
            }
            if (this.RespLiberacao != null)
            {
                this.RespLiberacao.Validate();
            }
            if (this.StatusEntregaTrem != null)
            {
                this.StatusEntregaTrem.Validate();
            }
        }
    }
}
