// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MaterialOperacao
    {
        /// <summary>
        /// Initializes a new instance of the MaterialOperacao class.
        /// </summary>
        public MaterialOperacao() { }

        /// <summary>
        /// Initializes a new instance of the MaterialOperacao class.
        /// </summary>
        public MaterialOperacao(int? idMaterialop = default(int?), int? idOperacaoFk = default(int?), string dnMaterial = default(string), double? qtMaterial = default(double?), int? idUnidadeFk = default(int?), int? idCategoriaItemFk = default(int?), int? idDepositoFk = default(int?), int? idCtLocalizacaoFk = default(int?), bool? rlReserva = default(bool?), string dsLocalEntrega = default(string), string nmRecebedor = default(string), BaseModel baseModel = default(BaseModel), CategoriaItem categoriaItem = default(CategoriaItem), OperacaoOrdem operacaoOrdem = default(OperacaoOrdem), UnidadeMedida unidadeMedida = default(UnidadeMedida), CentroLocalizacao centroLocalizacao = default(CentroLocalizacao), Deposito deposito = default(Deposito))
        {
            IdMaterialop = idMaterialop;
            IdOperacaoFk = idOperacaoFk;
            DnMaterial = dnMaterial;
            QtMaterial = qtMaterial;
            IdUnidadeFk = idUnidadeFk;
            IdCategoriaItemFk = idCategoriaItemFk;
            IdDepositoFk = idDepositoFk;
            IdCtLocalizacaoFk = idCtLocalizacaoFk;
            RlReserva = rlReserva;
            DsLocalEntrega = dsLocalEntrega;
            NmRecebedor = nmRecebedor;
            BaseModel = baseModel;
            CategoriaItem = categoriaItem;
            OperacaoOrdem = operacaoOrdem;
            UnidadeMedida = unidadeMedida;
            CentroLocalizacao = centroLocalizacao;
            Deposito = deposito;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_materialop")]
        public int? IdMaterialop { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_operacao_fk")]
        public int? IdOperacaoFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dn_material")]
        public string DnMaterial { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "qt_material")]
        public double? QtMaterial { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_unidade_fk")]
        public int? IdUnidadeFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_categoria_item_fk")]
        public int? IdCategoriaItemFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_deposito_fk")]
        public int? IdDepositoFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_ct_localizacao_fk")]
        public int? IdCtLocalizacaoFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rl_reserva")]
        public bool? RlReserva { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ds_local_entrega")]
        public string DsLocalEntrega { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nm_recebedor")]
        public string NmRecebedor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseModel")]
        public BaseModel BaseModel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CategoriaItem")]
        public CategoriaItem CategoriaItem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OperacaoOrdem")]
        public OperacaoOrdem OperacaoOrdem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnidadeMedida")]
        public UnidadeMedida UnidadeMedida { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CentroLocalizacao")]
        public CentroLocalizacao CentroLocalizacao { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Deposito")]
        public Deposito Deposito { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.DnMaterial != null)
            {
                if (this.DnMaterial.Length > 40)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "DnMaterial", 40);
                }
                if (this.DnMaterial.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "DnMaterial", 0);
                }
            }
            if (this.NmRecebedor != null)
            {
                if (this.NmRecebedor.Length > 50)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "NmRecebedor", 50);
                }
                if (this.NmRecebedor.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "NmRecebedor", 0);
                }
            }
            if (this.CategoriaItem != null)
            {
                this.CategoriaItem.Validate();
            }
            if (this.OperacaoOrdem != null)
            {
                this.OperacaoOrdem.Validate();
            }
            if (this.CentroLocalizacao != null)
            {
                this.CentroLocalizacao.Validate();
            }
        }
    }
}
