// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class StatusTrem
    {
        /// <summary>
        /// Initializes a new instance of the StatusTrem class.
        /// </summary>
        public StatusTrem() { }

        /// <summary>
        /// Initializes a new instance of the StatusTrem class.
        /// </summary>
        public StatusTrem(int? idStTrem = default(int?), string dsStTrem = default(string), string dsGrStTrem = default(string), BaseModel baseModel = default(BaseModel))
        {
            IdStTrem = idStTrem;
            DsStTrem = dsStTrem;
            DsGrStTrem = dsGrStTrem;
            BaseModel = baseModel;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_st_trem")]
        public int? IdStTrem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ds_st_trem")]
        public string DsStTrem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ds_gr_st_trem")]
        public string DsGrStTrem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseModel")]
        public BaseModel BaseModel { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.DsStTrem != null)
            {
                if (this.DsStTrem.Length > 50)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "DsStTrem", 50);
                }
                if (this.DsStTrem.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "DsStTrem", 0);
                }
            }
            if (this.DsGrStTrem != null)
            {
                if (this.DsGrStTrem.Length > 6)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "DsGrStTrem", 6);
                }
                if (this.DsGrStTrem.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "DsGrStTrem", 0);
                }
            }
        }
    }
}
