// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TipoCentroTrabalho
    {
        /// <summary>
        /// Initializes a new instance of the TipoCentroTrabalho class.
        /// </summary>
        public TipoCentroTrabalho() { }

        /// <summary>
        /// Initializes a new instance of the TipoCentroTrabalho class.
        /// </summary>
        public TipoCentroTrabalho(int? idTpCentroTrabalho = default(int?), string cdSap = default(string), string dsTpCentroTrabalho = default(string), BaseModel baseModel = default(BaseModel))
        {
            IdTpCentroTrabalho = idTpCentroTrabalho;
            CdSap = cdSap;
            DsTpCentroTrabalho = dsTpCentroTrabalho;
            BaseModel = baseModel;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_tp_centro_trabalho")]
        public int? IdTpCentroTrabalho { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cd_sap")]
        public string CdSap { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ds_tp_centro_trabalho")]
        public string DsTpCentroTrabalho { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseModel")]
        public BaseModel BaseModel { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.CdSap != null)
            {
                if (this.CdSap.Length > 10)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CdSap", 10);
                }
                if (this.CdSap.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CdSap", 0);
                }
            }
            if (this.DsTpCentroTrabalho != null)
            {
                if (this.DsTpCentroTrabalho.Length > 150)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "DsTpCentroTrabalho", 150);
                }
                if (this.DsTpCentroTrabalho.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "DsTpCentroTrabalho", 0);
                }
            }
        }
    }
}
