// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TipoOrdem
    {
        /// <summary>
        /// Initializes a new instance of the TipoOrdem class.
        /// </summary>
        public TipoOrdem() { }

        /// <summary>
        /// Initializes a new instance of the TipoOrdem class.
        /// </summary>
        public TipoOrdem(int? idTpOrdem = default(int?), string cdSap = default(string), string dsTpOrdem = default(string), BaseModel baseModel = default(BaseModel))
        {
            IdTpOrdem = idTpOrdem;
            CdSap = cdSap;
            DsTpOrdem = dsTpOrdem;
            BaseModel = baseModel;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_tp_ordem")]
        public int? IdTpOrdem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cd_sap")]
        public string CdSap { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ds_tp_ordem")]
        public string DsTpOrdem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseModel")]
        public BaseModel BaseModel { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.CdSap != null)
            {
                if (this.CdSap.Length > 3)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CdSap", 3);
                }
                if (this.CdSap.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CdSap", 0);
                }
            }
            if (this.DsTpOrdem != null)
            {
                if (this.DsTpOrdem.Length > 50)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "DsTpOrdem", 50);
                }
                if (this.DsTpOrdem.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "DsTpOrdem", 0);
                }
            }
        }
    }
}
