// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Trem
    {
        /// <summary>
        /// Initializes a new instance of the Trem class.
        /// </summary>
        public Trem() { }

        /// <summary>
        /// Initializes a new instance of the Trem class.
        /// </summary>
        public Trem(int? idTrem = default(int?), string cdSap = default(string), int? idDocMedicaoFk = default(int?), string nmTrem = default(string), int? idFrotaFk = default(int?), int? idLinhaOrigemFk = default(int?), int? idPatioFk = default(int?), int? idLinhaAtualFk = default(int?), bool? stManobra = default(bool?), int? stTrem = default(int?), bool? stDisponivel = default(bool?), BaseModel baseModel = default(BaseModel), Frota frota = default(Frota), Documento documento = default(Documento), Linha linhaOrigem = default(Linha), Linha linhaAtual = default(Linha), Patio patio = default(Patio), StatusTrem statusTrem = default(StatusTrem))
        {
            IdTrem = idTrem;
            CdSap = cdSap;
            IdDocMedicaoFk = idDocMedicaoFk;
            NmTrem = nmTrem;
            IdFrotaFk = idFrotaFk;
            IdLinhaOrigemFk = idLinhaOrigemFk;
            IdPatioFk = idPatioFk;
            IdLinhaAtualFk = idLinhaAtualFk;
            StManobra = stManobra;
            StTrem = stTrem;
            StDisponivel = stDisponivel;
            BaseModel = baseModel;
            Frota = frota;
            Documento = documento;
            LinhaOrigem = linhaOrigem;
            LinhaAtual = linhaAtual;
            Patio = patio;
            StatusTrem = statusTrem;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_trem")]
        public int? IdTrem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cd_sap")]
        public string CdSap { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_doc_medicao_fk")]
        public int? IdDocMedicaoFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nm_trem")]
        public string NmTrem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_frota_fk")]
        public int? IdFrotaFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_linha_origem_fk")]
        public int? IdLinhaOrigemFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_patio_fk")]
        public int? IdPatioFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_linha_atual_fk")]
        public int? IdLinhaAtualFk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "st_manobra")]
        public bool? StManobra { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "st_trem")]
        public int? StTrem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "st_disponivel")]
        public bool? StDisponivel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseModel")]
        public BaseModel BaseModel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Frota")]
        public Frota Frota { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Documento")]
        public Documento Documento { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LinhaOrigem")]
        public Linha LinhaOrigem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LinhaAtual")]
        public Linha LinhaAtual { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Patio")]
        public Patio Patio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StatusTrem")]
        public StatusTrem StatusTrem { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.CdSap != null)
            {
                if (this.CdSap.Length > 3)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CdSap", 3);
                }
                if (this.CdSap.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CdSap", 0);
                }
            }
            if (this.Documento != null)
            {
                this.Documento.Validate();
            }
            if (this.LinhaOrigem != null)
            {
                this.LinhaOrigem.Validate();
            }
            if (this.LinhaAtual != null)
            {
                this.LinhaAtual.Validate();
            }
            if (this.Patio != null)
            {
                this.Patio.Validate();
            }
            if (this.StatusTrem != null)
            {
                this.StatusTrem.Validate();
            }
        }
    }
}
