// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PM.WebServices.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Zona
    {
        /// <summary>
        /// Initializes a new instance of the Zona class.
        /// </summary>
        public Zona() { }

        /// <summary>
        /// Initializes a new instance of the Zona class.
        /// </summary>
        public Zona(int? idZona = default(int?), string nmZona = default(string), BaseModel baseModel = default(BaseModel))
        {
            IdZona = idZona;
            NmZona = nmZona;
            BaseModel = baseModel;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id_zona")]
        public int? IdZona { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nm_zona")]
        public string NmZona { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseModel")]
        public BaseModel BaseModel { get; set; }

    }
}
